//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by CMS Entity ID Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Runtime.CMS
{
    public static class CMs
    {
        public static class Audio
        {
            public static class SFX
            {
                public const string SFXTest = "CMS/Audio/SFX/SFXTest";
            }
            public const string AmbientTest = "CMS/Audio/AmbientTest";
        }
        public static class CommandBlocks
        {
            public const string Block1 = "CMS/CommandBlocks/Block1";
        }
        public static class Configs
        {
            public const string DialogReference = "CMS/Configs/DialogReference";
            public const string EnemiesByLevel = "CMS/Configs/EnemiesByLevel";
            public const string MockEnemyConfig = "CMS/Configs/MockEnemyConfig";
            public const string PlayerConfig = "CMS/Configs/PlayerConfig";
        }
    }
}
