//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by CMS Entity ID Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Runtime.CMS
{
    public static class CMs
    {
        public static class Audio
        {
            public static class SFX
            {
                public const string SFXTest = "CMS/Audio/SFX/SFXTest";
            }
            public const string AmbientTest = "CMS/Audio/AmbientTest";
        }
        public static class Gameplay
        {
            public const string DefaultGrid = "CMS/Gameplay/DefaultGrid";
            public const string HUD = "CMS/Gameplay/HUD";
        }
    }
}
